# Generated by Django 4.1.3 on 2023-10-02 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_rename_catagory_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="category", new_name="categorys",
        ),
    ]
